#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 15 17:20:22 IDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.6.zip
